.github/workflows/module-plugin-test.yml
Looks like GitHub Actions runs everything under `run` as a single command.
I hate debugging GitHub Actions, particularly one like this where it's not obvious how to run it locally.
=> Add missing `;`

.github/workflows/module-plugin-test.yml
We shouldn't assume the package will match the repo. This is due to migrating packages from GitHub-hosted `newfold-labs` packages to npmjs-hosted `newfold` packages. This is required for the test workflows in the updated e-commerce repo for the workflows to sync the package changes into the plugin package for testing.
This is one reason why this workflow is failing: https://github.com/newfold-labs/wp-module-ecommerce/pull/403 now that https://github.com/newfold-labs/wp-module-ecommerce/pull/404 is merged. The package name doesn't match the repo name anymore, so we need a new value for it.
=> add input for sync package name

.github/workflows/i18n-crowdin-download.yml, .github/workflows/i18n-crowdin-upload.yml
This PR Fixes Crowdin workflow issues with GITHUB_TOKEN.
=> Fix Crowdin workflow issues with GITHUB_TOKEN

.github/workflows/i18n-crowdin-download.yml, .github/workflows/i18n-crowdin-upload.yml
=> Fix Crowdin workflow issues

.github/workflows/i18n-crowdin-download.yml, .github/workflows/i18n-update.yml
This PR adds i18n-update workflow to automate the i18n source files (.pot, .po, .php, .json) generation and updation. 
See: https://jira.newfold.com/browse/PRESS11-154
=> Add i18n-update workflow to automate the i18n source file generation and updation.

.github/workflows/module-plugin-test.yml
#22 included an incorrect hash value for the `upload-artifact` action. This fixes that SHA and updates the action to the latest version.
=> Use correct SHA values for uload-artifact.

.github/workflows/module-plugin-test.yml
These quotes broke things as far as accessing the debug.log.
=> fix debug log step in cypress workflow

.github/workflows/module-plugin-test.yml
Found a couple small issues with the workflow:
- only check in the module tests/cypress/integration directory for test files
- only attempt to run tests in the cypress/integration directory
- when running remaining tests, also run plugin-level tests
=> Fix cypress tests directory issue

.github/workflows/i18n-crowdin-download.yml, .github/workflows/i18n-update.yml
Fix pull request issue with the i18n-update workflow.
=> Fix pull request issue with the i18n-update workflow 

.github/workflows/module-prep-release.yml, .github/workflows/reusable-module-prep-release.yml
Example of use in onboarding here: https://github.com/newfold-labs/wp-module-onboarding/actions/workflows/newfold-prep-release.yml
This workflow will run the version bump script in the module - until we can get all modules to manage versioning in a consistent way, this feels like the best option. 
But we could consider options. Here are some ideas for improvements (I don't think any are blockers, but if we can get any high-impact and low-effort improvements in already, no reason not to):
- The module workflow could pass the files with version constants as inputs. This reusable workflow could easily replicate the versioning step currently done via the `set-versoin-bump` script. (a la https://github.com/phips28/gh-action-bump-version)
- Modules that don't have any version constants that …
=> Add prep release workflow

.github/workflows/reusable-module-prep-release.yml
This removes the dependency on a set-version-bump script in the module. The workflow does the version bumps in the js & PHP file, and accepts these as new inputs.
Adds better PR content. Attempts to pull merged PRs since last release.
Also adds a workflow summary that outputs the version changes and links to the created PR.
I did some testing with it in the data module. See https://github.com/newfold-labs/wp-module-data/actions/runs/14934260193
This will make it much easier to incorporate in more modules since we won't need to add a script file, but can pass the files that have version constants as inputs. These default to the most common, package.json for js (which I don't think we have any instances of something else being used), and bootstrap.php which is the most common PHP file with …
=> Update prep release workflow

.github/workflows/i18n-crowdin-download.yml, .github/workflows/i18n-update.yml, .github/workflows/module-plugin-test.yml, .github/workflows/reusable-workflow-lint.yml, .github/workflows/verify-module-plugin-test.yml
For workflows, permissions should be set to none by default with additional permissions being configured at the job level.
=> Prevent permissions from being too generous

.github/workflows/i18n-crowdin-download.yml, .github/workflows/i18n-crowdin-upload.yml, .github/workflows/i18n-update.yml, .github/workflows/module-plugin-test.yml, .github/workflows/reusable-module-prep-release.yml
Persisting the credential in the `.git/config` (which is the default for actions/checkout) is non-ideal unless actually needed.
Adds the `persist-credentials` input set to `false`.
=> Do not persist credentials for checkouts in GitHub Actions

.github/workflows/reusable-module-prep-release.yml
Specify tag-version-prefix as empty so we don't get a `v` in our version
=> Fix npm version command

.github/workflows/module-plugin-test.yml, .github/workflows/reusable-module-prep-release.yml
This hardens workflow files against template injection.
=> Harden workflows against template expansion.

.github/workflows/reusable-cloudflare-worker-deploy.yml
This adds the passed `contents: read` permissions from calling workflows to ensure `actions/checkout` can appropriately access repositories.
See a [failing workflow here](https://github.com/newfold-labs/cf-worker-site-classification-api/actions/runs/15143003725/job/42571739192) and the [companion pull request on that repo](https://github.com/newfold-labs/cf-worker-site-classification-api/pull/3).
=> Add `contents: read` permissions for checkouts.

.github/workflows/reusable-cloudflare-worker-deploy.yml
This adds the ability to run `npm install` before deploying a Cloudflare Worker through the use if a new `npm-install` input variable. The default is `false`. But when `true` is passed, actions/setup-node` will be used to configure the appropriate version of Node.js/npm as defined in the `.nvmrc` file. If one is not present, the workflow falls back to any values specified in `engines.node` within the `package.json` file.
=> Add support for installing dependencies before deploying Cloudflare Workers

.github/workflows/reusable-module-prep-release.yml, .github/workflows/reusable-plugin-prep-release.yml
This is some minor changes to docs and step names to make these steps consistent with each other. They both had some recent changes, and I wanted to keep them in sync with each other.
=> Sync updates to keep these workflows consistent

.github/workflows/reusable-plugin-prep-release.yml
I noticed in a recent automated commit in bluehost plugin that the version wasn't displayed properly and think it's due to this typo. 
See: https://github.com/newfold-labs/wp-plugin-bluehost/pull/304/commits/c4127999afdf2e2a41eadd0d3e461cf733041ab6
=> fix typo - missing `{`

.github/workflows/reusable-azure-ai-translate.yml
This is a second possible way to account for when the `auto-translate/BASE` branch already exists without a corresponding pull request by treating `auto-translate/*` branches as reserved. This will: 
- Check for a pre-existing branch on the remote repository when no pull request exists for the branch.
- Delete the branch remotely to ensure the branch is accurate and up to date.
Other possible approach: #52.
=> Account for pre-existing branches without a pull request: option 2

.github/workflows/reusable-azure-ai-translate.yml
This fixes a condition that was mistakenly made reversed by me.
=> Fix conditions that check for deleting a branch

.github/workflows/reusable-azure-ai-translate.yml
This moves the translation Python script to a temporary directory instead of the working one. This avoids having to add the translation script to `.gitignore` for every repository.
=> Place translation script into temporary directory.

.github/workflows/reusable-azure-ai-translate.yml
Update Azure AI translate workflow to store the translation script files in runner temp directory.
=> Update Translate workflow to store the translation script in Temp Directory

.github/workflows/reusable-translations.yml
The Azure step did not have `overwrite` set to `true`.
=> Overwrite pre-existing artifacts

.github/workflows/reusable-translations.yml
When multiple notices are output, it needs to be more clear which step is producing them.
See https://github.com/newfold-labs/wp-module-sso/actions/runs/16026449635 for an example.
=> Clarify output notices.
